// =========================================================================
// CIVICSOLVE AI — JHARKHAND 24 DISTRICTS ACCURATE GIS & CIVIC DATASET
// Complete administrative dataset for all 24 districts of Jharkhand
// =========================================================================

export const JHARKHAND_DISTRICTS = [
  {
    id: 'ranchi',
    name: 'Ranchi',
    nameHi: 'राँची',
    division: 'South Chotanagpur (दक्षिणी छोटानागपुर)',
    headquarters: 'Ranchi (राँची)',
    areaKm2: 5097,
    population: '29.1 Lakh',
    activeGrievances: 142,
    resolvedGrievances: 3840,
    helpline: '0651-2214010 / 181',
    emergencyContact: 'dc-ranchi@nic.in',
    keyServices: ['Abua Awas', 'Ranchi Water Mission', 'Smart City Grievances', 'Birsa Kisan Hub'],
    hotspotCategory: 'water',
    topIssues: ['Industrial Runoff in Subernarekha', 'Ward 14 Drinking Water Pipe Leakage', 'Ratu Road Traffic Drainage'],
    mapCoords: { x: 380, y: 310 }, // Relative SVG coordinate
    svgPath: 'M 345 285 L 420 280 L 440 330 L 400 355 L 340 335 Z'
  },
  {
    id: 'dhanbad',
    name: 'Dhanbad',
    nameHi: 'धनबाद',
    division: 'North Chotanagpur (उत्तरी छोटानागपुर)',
    headquarters: 'Dhanbad (धनबाद)',
    areaKm2: 2040,
    population: '26.8 Lakh',
    activeGrievances: 118,
    resolvedGrievances: 2950,
    helpline: '0326-2311217 / 181',
    emergencyContact: 'dc-dhanbad@nic.in',
    keyServices: ['Mine Safety Redressal', 'Coal Belt Air Monitoring', 'Urban PDS', 'DMFT Scheme'],
    hotspotCategory: 'mining',
    topIssues: ['Jharia Coal Mine Subsurface Gas', 'Damodar Ash Pond Overflow', 'Govindpur Water Tank Defect'],
    mapCoords: { x: 500, y: 240 },
    svgPath: 'M 475 220 L 530 215 L 545 260 L 490 265 Z'
  },
  {
    id: 'east_singhbhum',
    name: 'East Singhbhum (Jamshedpur)',
    nameHi: 'पूर्वी सिंहभूम (जमशेदपुर)',
    division: 'Kolhan (कोल्हान)',
    headquarters: 'Jamshedpur (जमशेदपुर)',
    areaKm2: 3562,
    population: '22.9 Lakh',
    activeGrievances: 96,
    resolvedGrievances: 2710,
    helpline: '0657-2431002 / 181',
    emergencyContact: 'dc-esinghbhum@nic.in',
    keyServices: ['Subernarekha Flood Alert', 'Industrial Worker Welfare', 'Potka Tribal Health'],
    hotspotCategory: 'water',
    topIssues: ['Slag Dumping in Kharkai River', 'Jugsalai Drainage Clogging', 'Ghatshila Copper Effluent'],
    mapCoords: { x: 540, y: 400 },
    svgPath: 'M 505 375 L 575 365 L 585 435 L 525 440 Z'
  },
  {
    id: 'west_singhbhum',
    name: 'West Singhbhum (Chaibasa)',
    nameHi: 'पश्चिमी सिंहभूम (चाईबासा)',
    division: 'Kolhan (कोल्हान)',
    headquarters: 'Chaibasa (चाईबासा)',
    areaKm2: 7224,
    population: '15.0 Lakh',
    activeGrievances: 84,
    resolvedGrievances: 1890,
    helpline: '06582-256301 / 181',
    emergencyContact: 'dc-wsinghbhum@nic.in',
    keyServices: ['Saranda Forest Welfare', 'Iron Ore Mining DMFT', 'Tribal Healthcare Camps'],
    hotspotCategory: 'forest',
    topIssues: ['Saranda Solar Cold-Chain Disruption', 'Noamundi Red Dust Infiltration', 'Manoharpur Road Repair'],
    mapCoords: { x: 420, y: 430 },
    svgPath: 'M 375 390 L 475 385 L 485 480 L 390 485 Z'
  },
  {
    id: 'seraikela_kharsawan',
    name: 'Seraikela Kharsawan',
    nameHi: 'सरायकेला खरसावां',
    division: 'Kolhan (कोल्हान)',
    headquarters: 'Seraikela (सरायकेला)',
    areaKm2: 2657,
    population: '10.6 Lakh',
    activeGrievances: 52,
    resolvedGrievances: 1420,
    helpline: '06597-234201 / 181',
    emergencyContact: 'dc-seraikela@nic.in',
    keyServices: ['Adityapur Industrial Waste Action', 'Chhau Art Grants', 'Jal Jeevan Mission'],
    hotspotCategory: 'water',
    topIssues: ['Adityapur Industrial Effluent', 'Chandil Dam Fishermen Relief', 'Gamharia Piped Water'],
    mapCoords: { x: 470, y: 380 },
    svgPath: 'M 445 355 L 505 350 L 515 395 L 455 400 Z'
  },
  {
    id: 'bokaro',
    name: 'Bokaro',
    nameHi: 'बोकारो',
    division: 'North Chotanagpur (उत्तरी छोटानागपुर)',
    headquarters: 'Bokaro Steel City (बोकारो)',
    areaKm2: 2883,
    population: '20.6 Lakh',
    activeGrievances: 78,
    resolvedGrievances: 2310,
    helpline: '06542-242299 / 181',
    emergencyContact: 'dc-bokaro@nic.in',
    keyServices: ['Steel Plant Air Grievance', 'Tenughat Dam Telemetry', 'Chas Municipal Services'],
    hotspotCategory: 'mining',
    topIssues: ['Damodar River Coal Siltation', 'Bermo Colliery Water Pollution', 'Chas City Solid Waste'],
    mapCoords: { x: 450, y: 260 },
    svgPath: 'M 420 245 L 480 235 L 490 280 L 430 285 Z'
  },
  {
    id: 'hazaribagh',
    name: 'Hazaribagh',
    nameHi: 'हजारीबाग',
    division: 'North Chotanagpur (उत्तरी छोटानागपुर)',
    headquarters: 'Hazaribagh (हजारीबाग)',
    areaKm2: 3555,
    population: '17.3 Lakh',
    activeGrievances: 65,
    resolvedGrievances: 2100,
    helpline: '06546-264211 / 181',
    emergencyContact: 'dc-hazaribagh@nic.in',
    keyServices: ['Canary Hill Forest Protection', 'Agri Cold-Storage Grievance', 'Konar Dam Water'],
    hotspotCategory: 'forest',
    topIssues: ['Barhi NH-33 Flyover Bottleneck', 'Pugmil Piped Water Failure', 'Barkagaon Land Compensation'],
    mapCoords: { x: 370, y: 220 },
    svgPath: 'M 335 195 L 415 190 L 425 245 L 345 250 Z'
  },
  {
    id: 'ramgarh',
    name: 'Ramgarh',
    nameHi: 'रामगढ़',
    division: 'North Chotanagpur (उत्तरी छोटानागपुर)',
    headquarters: 'Ramgarh Cantonment (रामगढ़)',
    areaKm2: 1341,
    population: '9.5 Lakh',
    activeGrievances: 49,
    resolvedGrievances: 1380,
    helpline: '06553-261500 / 181',
    emergencyContact: 'dc-ramgarh@nic.in',
    keyServices: ['Patratu Tourism & Power Hub', 'Rajrappa Pilgrim Facilities', 'Kuju Coal Dust Redressal'],
    hotspotCategory: 'mining',
    topIssues: ['Nalkari River Flyash Contamination', 'Giddi Washery Discharge', 'Ramgarh Cantt Water Shortage'],
    mapCoords: { x: 400, y: 270 },
    svgPath: 'M 380 255 L 430 250 L 440 285 L 390 290 Z'
  },
  {
    id: 'giridih',
    name: 'Giridih',
    nameHi: 'गिरिडीह',
    division: 'North Chotanagpur (उत्तरी छोटानागपुर)',
    headquarters: 'Giridih (गिरिडीह)',
    areaKm2: 4962,
    population: '24.4 Lakh',
    activeGrievances: 91,
    resolvedGrievances: 2540,
    helpline: '06532-222044 / 181',
    emergencyContact: 'dc-giridih@nic.in',
    keyServices: ['Parasnath Pilgrim Welfare', 'Mica Belt Healthcare Hub', 'Usri Fall Eco-Services'],
    hotspotCategory: 'forest',
    topIssues: ['Tisri Mica Mining Dust', 'Parasnath Foothill Waste', 'Bagodar Solar Micro-Grid'],
    mapCoords: { x: 460, y: 170 },
    svgPath: 'M 425 145 L 500 135 L 515 205 L 440 210 Z'
  },
  {
    id: 'koderma',
    name: 'Koderma',
    nameHi: 'कोडरमा',
    division: 'North Chotanagpur (उत्तरी छोटानागपुर)',
    headquarters: 'Koderma (कोडरमा)',
    areaKm2: 1500,
    population: '7.2 Lakh',
    activeGrievances: 38,
    resolvedGrievances: 1120,
    helpline: '06534-222014 / 181',
    emergencyContact: 'dc-koderma@nic.in',
    keyServices: ['Tilaiya Dam Water Supply', 'Mica Scraps Legal Assistance', 'Jhumri Telaiya Sanitation'],
    hotspotCategory: 'mining',
    topIssues: ['Domchanch Stone Crusher Dust', 'Tilaiya Catchment Encroachment', 'Chandwara Power Trip'],
    mapCoords: { x: 380, y: 150 },
    svgPath: 'M 350 130 L 415 125 L 425 175 L 360 180 Z'
  },
  {
    id: 'chatra',
    name: 'Chatra',
    nameHi: 'चतरा',
    division: 'North Chotanagpur (उत्तरी छोटानागपुर)',
    headquarters: 'Chatra (चतरा)',
    areaKm2: 3718,
    population: '10.4 Lakh',
    activeGrievances: 45,
    resolvedGrievances: 1290,
    helpline: '06541-252210 / 181',
    emergencyContact: 'dc-chatra@nic.in',
    keyServices: ['Tandwa NTPC Flyash Monitoring', 'Maa Bhadrakali Temple Facilities', 'Solar Agri Pumps'],
    hotspotCategory: 'mining',
    topIssues: ['Amrapali Coal Transportation Road', 'Hunterganj Drought Relief', 'Simaria PHC Staffing'],
    mapCoords: { x: 290, y: 180 },
    svgPath: 'M 255 155 L 335 150 L 345 215 L 265 220 Z'
  },
  {
    id: 'palamu',
    name: 'Palamu (Daltonganj)',
    nameHi: 'पलामू (मेदिनीनगर)',
    division: 'Palamu (पलामू)',
    headquarters: 'Medininagar / Daltonganj (मेदिनीनगर)',
    areaKm2: 4393,
    population: '19.4 Lakh',
    activeGrievances: 88,
    resolvedGrievances: 2450,
    helpline: '06562-222238 / 181',
    emergencyContact: 'dc-palamu@nic.in',
    keyServices: ['North Koel Water Project', 'Drought-Prone Agri Shield', 'Betla Border Animal Alerts'],
    hotspotCategory: 'forest',
    topIssues: ['Amanat River Water Depletion', 'Medininagar Town Water Rationing', 'Lesliganj Canal Silt'],
    mapCoords: { x: 200, y: 200 },
    svgPath: 'M 160 170 L 245 165 L 255 240 L 170 245 Z'
  },
  {
    id: 'garhwa',
    name: 'Garhwa',
    nameHi: 'गढ़वा',
    division: 'Palamu (पलामू)',
    headquarters: 'Garhwa (गढ़वा)',
    areaKm2: 4093,
    population: '13.2 Lakh',
    activeGrievances: 62,
    resolvedGrievances: 1680,
    helpline: '06561-222224 / 181',
    emergencyContact: 'dc-garhwa@nic.in',
    keyServices: ['Son River Lift Irrigation', 'Bhavnathpur Limestone Welfare', 'Kanhar Basin Alert'],
    hotspotCategory: 'water',
    topIssues: ['Ranka Block Ground Water Crisis', 'Kandi Panchayat Solar Pump Failure', 'Garhwa Nagar Untreated Sewage'],
    mapCoords: { x: 120, y: 170 },
    svgPath: 'M 80 135 L 160 130 L 170 220 L 90 225 Z'
  },
  {
    id: 'latehar',
    name: 'Latehar',
    nameHi: 'लातेहार',
    division: 'Palamu (पलामू)',
    headquarters: 'Latehar (लातेहार)',
    areaKm2: 4291,
    population: '7.3 Lakh',
    activeGrievances: 41,
    resolvedGrievances: 1090,
    helpline: '06565-242205 / 181',
    emergencyContact: 'dc-latehar@nic.in',
    keyServices: ['Betla National Park Eco-Alerts', 'Netarhat Hill Tourism Support', 'Tribal Forest Rights'],
    hotspotCategory: 'forest',
    topIssues: ['Mahuadanr Solar Vaccine Store', 'Chandwa Thermal Flyash Infiltration', 'Garu Block Mobile Network'],
    mapCoords: { x: 240, y: 260 },
    svgPath: 'M 200 235 L 285 230 L 295 300 L 210 305 Z'
  },
  {
    id: 'lohardaga',
    name: 'Lohardaga',
    nameHi: 'लोहरदगा',
    division: 'South Chotanagpur (दक्षिणी छोटानागपुर)',
    headquarters: 'Lohardaga (लोहरदगा)',
    areaKm2: 1502,
    population: '4.6 Lakh',
    activeGrievances: 29,
    resolvedGrievances: 870,
    helpline: '06526-224022 / 181',
    emergencyContact: 'dc-lohardaga@nic.in',
    keyServices: ['Bauxite Mine DMFT Grants', 'Agri Cold-Storage Portal', 'Sankh River Basin Watch'],
    hotspotCategory: 'mining',
    topIssues: ['Bagru Bauxite Haul Road Dust', 'Kisko Block Water Table Drop', 'Peshrar Tribal Health Unit'],
    mapCoords: { x: 280, y: 320 },
    svgPath: 'M 250 295 L 315 290 L 325 345 L 260 350 Z'
  },
  {
    id: 'gumla',
    name: 'Gumla',
    nameHi: 'गुमला',
    division: 'South Chotanagpur (दक्षिणी छोटानागपुर)',
    headquarters: 'Gumla (गुमला)',
    areaKm2: 5360,
    population: '10.3 Lakh',
    activeGrievances: 57,
    resolvedGrievances: 1560,
    helpline: '06524-223201 / 181',
    emergencyContact: 'dc-gumla@nic.in',
    keyServices: ['Ragi & Millets Mission', 'Nagpheni Heritage Welfare', 'Tribal Handicrafts Support'],
    hotspotCategory: 'forest',
    topIssues: ['Chainpur Rural Bridge Repair', 'Bishunpur Lemongrass Processing', 'Palkot Solar Pumping Fault'],
    mapCoords: { x: 260, y: 390 },
    svgPath: 'M 215 350 L 305 345 L 315 435 L 225 440 Z'
  },
  {
    id: 'simdega',
    name: 'Simdega',
    nameHi: 'सिमडेगा',
    division: 'South Chotanagpur (दक्षिणी छोटानागपुर)',
    headquarters: 'Simdega (सिमडेगा)',
    areaKm2: 3774,
    population: '6.0 Lakh',
    activeGrievances: 34,
    resolvedGrievances: 940,
    helpline: '06525-225801 / 181',
    emergencyContact: 'dc-simdega@nic.in',
    keyServices: ['Hockey Cradle Sports Grants', 'Lac (लाह) Cultivation Aid', 'Kolebira PHC Telemetry'],
    hotspotCategory: 'forest',
    topIssues: ['Bano Railway Crossing Overbridge', 'Thethaitangar Piped Water Supply', 'Kurdeg Cold Storage'],
    mapCoords: { x: 270, y: 460 },
    svgPath: 'M 230 425 L 315 420 L 325 490 L 240 495 Z'
  },
  {
    id: 'khunti',
    name: 'Khunti',
    nameHi: 'खूंटी',
    division: 'South Chotanagpur (दक्षिणी छोटानागपुर)',
    headquarters: 'Khunti (खूंटी)',
    areaKm2: 2535,
    population: '5.3 Lakh',
    activeGrievances: 36,
    resolvedGrievances: 1040,
    helpline: '06528-220005 / 181',
    emergencyContact: 'dc-khunti@nic.in',
    keyServices: ['Bhagwan Birsa Munda Memorial Hub', 'Solar Village Program', 'Lac & Honey FPO Support'],
    hotspotCategory: 'forest',
    topIssues: ['Ulihatu Solar Microgrid Battery Issue', 'Torpa Organic Lac Value Chain', 'Murhu Block Water Tank'],
    mapCoords: { x: 350, y: 370 },
    svgPath: 'M 320 345 L 385 340 L 395 395 L 330 400 Z'
  },
  {
    id: 'deoghar',
    name: 'Deoghar',
    nameHi: 'देवघर',
    division: 'Santhal Pargana (संथाल परगना)',
    headquarters: 'Deoghar (देवघर)',
    areaKm2: 2477,
    population: '15.0 Lakh',
    activeGrievances: 72,
    resolvedGrievances: 2180,
    helpline: '06432-232230 / 181',
    emergencyContact: 'dc-deoghar@nic.in',
    keyServices: ['Baba Baidyanath Pilgrim Queue Hub', 'AIIMS Deoghar Transit', 'Peda Cluster Aid'],
    hotspotCategory: 'health',
    topIssues: ['Pilgrim Corridor Crowd Drainage', 'Madhupur Municipal Solid Waste', 'Jasidih Water Salinity'],
    mapCoords: { x: 530, y: 140 },
    svgPath: 'M 495 120 L 565 115 L 575 165 L 505 170 Z'
  },
  {
    id: 'dumka',
    name: 'Dumka (Sub-Capital)',
    nameHi: 'दुमका (उप-राजधानी)',
    division: 'Santhal Pargana (संथाल परगना)',
    headquarters: 'Dumka (दुमका)',
    areaKm2: 3761,
    population: '13.2 Lakh',
    activeGrievances: 68,
    resolvedGrievances: 1980,
    helpline: '06434-222204 / 181',
    emergencyContact: 'dc-dumka@nic.in',
    keyServices: ['Massanjore Dam Fishery Aid', 'Phulo Jhano Medical Support', 'Tribal Land Records Hub'],
    hotspotCategory: 'water',
    topIssues: ['Mayurakshi River Desiltation', 'Jariadih PHC Ambulance Delay', 'Ranishwar Solar Irrigation'],
    mapCoords: { x: 590, y: 150 },
    svgPath: 'M 555 130 L 625 125 L 635 185 L 565 190 Z'
  },
  {
    id: 'godda',
    name: 'Godda',
    nameHi: 'गोड्डा',
    division: 'Santhal Pargana (संथाल परगना)',
    headquarters: 'Godda (गोड्डा)',
    areaKm2: 2266,
    population: '13.1 Lakh',
    activeGrievances: 54,
    resolvedGrievances: 1470,
    helpline: '06422-222202 / 181',
    emergencyContact: 'dc-godda@nic.in',
    keyServices: ['ECL Coal Mining Compensation', 'Silk & Tussar Weaver Aid', 'Sundar Dam Water'],
    hotspotCategory: 'mining',
    topIssues: ['Mahagama Coal Dumper Road Safety', 'Poraiyahat Ground Water Fluoride', 'Boarijor Solar Cold-Chain'],
    mapCoords: { x: 610, y: 100 },
    svgPath: 'M 580 80 L 640 75 L 650 125 L 590 130 Z'
  },
  {
    id: 'sahibganj',
    name: 'Sahibganj',
    nameHi: 'साहिबगंज',
    division: 'Santhal Pargana (संथाल परगना)',
    headquarters: 'Sahibganj (साहिबगंज)',
    areaKm2: 2063,
    population: '11.5 Lakh',
    activeGrievances: 58,
    resolvedGrievances: 1610,
    helpline: '06436-222002 / 181',
    emergencyContact: 'dc-sahibganj@nic.in',
    keyServices: ['Ganga Inland Waterway Multi-Modal Hub', 'Fossil Park Eco-Zone', 'Stone Quarry Regulation'],
    hotspotCategory: 'water',
    topIssues: ['Ganga River Bank Erosion at Rajmahal', 'Stone Crusher PM10 Emissions', 'Borio Malaria Outbreak Alert'],
    mapCoords: { x: 650, y: 80 },
    svgPath: 'M 620 60 L 680 55 L 690 105 L 630 110 Z'
  },
  {
    id: 'pakur',
    name: 'Pakur',
    nameHi: 'पाकुड़',
    division: 'Santhal Pargana (संथाल परगना)',
    headquarters: 'Pakur (पाकुड़)',
    areaKm2: 1811,
    population: '9.0 Lakh',
    activeGrievances: 47,
    resolvedGrievances: 1250,
    helpline: '06435-222055 / 181',
    emergencyContact: 'dc-pakur@nic.in',
    keyServices: ['Beedi Worker Healthcare Fund', 'Black Stone Quarry Worker Welfare', 'Paharia Primitive Tribe Aid'],
    hotspotCategory: 'health',
    topIssues: ['Hiranpur Bidi Worker Lung Health Screening', 'Littipara Deep Borewell Silt', 'Amrapara Solar Grid'],
    mapCoords: { x: 640, y: 150 },
    svgPath: 'M 610 130 L 670 125 L 680 175 L 620 180 Z'
  },
  {
    id: 'jamtara',
    name: 'Jamtara',
    nameHi: 'जामताड़ा',
    division: 'Santhal Pargana (संथाल परगना)',
    headquarters: 'Jamtara (जामताड़ा)',
    areaKm2: 1811,
    population: '7.9 Lakh',
    activeGrievances: 42,
    resolvedGrievances: 1190,
    helpline: '06433-222202 / 181',
    emergencyContact: 'dc-jamtara@nic.in',
    keyServices: ['Community Digital Literacy Hubs', 'Cyber Hygiene Grievances', 'Ajay River Lift Irrigation'],
    hotspotCategory: 'health',
    topIssues: ['Kundahit Block PDS Biometric Timeout', 'Mihijam Railway Town Sewage', 'Narayanpur PHC Doctor Shortage'],
    mapCoords: { x: 550, y: 200 },
    svgPath: 'M 520 180 L 580 175 L 590 225 L 530 230 Z'
  }
];

export function getDistrictById(id) {
  return JHARKHAND_DISTRICTS.find(d => d.id === id) || JHARKHAND_DISTRICTS[0];
}

export function getAllDistricts() {
  return JHARKHAND_DISTRICTS;
}
